### ISSUE TITLE
Use linkify-it for parsing the links

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/draft-js-plugin-editor#18]

**Comment by nikgraf** [comment]
@tasti is using https://github.com/markdown-it/linkify-it in here https://www.npmjs.com/package/react-linkify

Looks like this would be better than what we do right now :smile:

**Comment by tasti** [comment]
Originally I wrote my own regex to parse through the text too, and ended up using `linkify-it` so that it would be more rigorous. I definitely recommend :+1:

**Comment by nikgraf** [comment]
thx :smile:
