### ISSUE TITLE
Change Sticker plugin to allow passing in meta data to the StickerSelect

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/draft-js-plugin-editor#33]
This is important to make sure people can build more advanced selects. I'm not sure if we should have a nesting inside stickers like

```
stickers: {
  stickers: {}
  meta:{}
}
```

or if we simply pass the whole config down and meta data should be attached to it.

**Comment by mxstbr** [comment]
What about `data`? That would be the cleanest solution I can think of:

```JS
stickers: {
  data: {},
  meta: {},
}
```

**Comment by nikgraf** [comment]
good idea!
