### ISSUE TITLE
add key property to avoid warning

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/draft-js-plugin-editor#34]
I somewhere forgot to add the key prop. Now there is warning.

**Comment by mxstbr** [comment]
https://github.com/nikgraf/draft-js-plugin-editor/commit/8f51e4e614eb33862fe707cd6f5714a1eeb33276 ?

**Comment by mxstbr** [comment]
No warning for me anymore, so I'm going to assume you mean the one fixed in https://github.com/nikgraf/draft-js-plugin-editor/commit/8f51e4e614eb33862fe707cd6f5714a1eeb33276
