### ISSUE TITLE
Fix focus issue

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/draft-js-plugin-editor#44]
When clicking somewhere in the editor it should mimic the native behaviour and set the cursor at the end.

**Comment by steviesama** [comment]
I'm not using plugins, but I see this behavior in the core project.

**Comment by steviesama** [comment]
Here is the issue I opened for it yesterday.
[https://github.com/facebook/draft-js/issues/405](https://github.com/facebook/draft-js/issues/405)

**Comment by nikgraf** [comment]
thx for reporting it @steviesama
