### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/draft-js-plugin-editor#55]
For some reason the editor is way slower than what you can see on the original pages. Investigate the bottle neck & fix it.

First ideas:
- onChange is heavy
- componentWillReceiveProperties is slowing down  
- when plugins are initialised we can store which functions actually should be cold and don't have to loop over every plugin

**Comment by jpuri** [comment]
Interesting issue, we had something similar with controlled input box in belle.

**Comment by nikgraf** [comment]
By investigating a bit more I figured the Prism highlighting is quite expensive and especially with a large state or rapid changes the editor slowed down significantly.

Fixed it here: https://github.com/nikgraf/draft-js-plugin-editor/commit/a83febdffd58374a11880a34e8d32aebfa4fd11d

/cc @jpuri & @mxstbr you might find this useful for future projects
