### ISSUE TITLE
Create a chat room to allow communication with other developers

### ISSUE THREAD

**Issue by mitermayer** [nikgraf/draft-js-plugin-editor#56]
I like the idea of the direction that this is taking, would be great if we had a way to communicate either via discuss, irc, hipchat or slack, this way would be a lot easier to contribute to this project

**Comment by nikgraf** [comment]
Great idea, we opened a #plugin-editor channel in the draftJS Slack. You can sign in here https://draftjs.herokuapp.com/

**Comment by nikgraf** [comment]
alos just added it to the readme: https://github.com/nikgraf/draft-js-plugin-editor/commit/e760915a88b1bd9538d2a01ba9f39c37db082717
