### ISSUE TITLE
should <MentionSearch> be rendered outside the contentEditable editor

### ISSUE THREAD

**Issue by filod** [nikgraf/draft-js-plugin-editor#59]
some weird behaviors happen when <MentionSearch> show up:

- mouse click can not focus the cursor to the end of line
- use `cmd + →` can not jump to the end of line

![image](https://cloud.githubusercontent.com/assets/679897/13630634/4aac2668-e61b-11e5-87a5-d81396d1fdc5.png)

maybe use something like https://github.com/tajo/react-portal to solve this?

**Comment by nikgraf** [comment]
super valuable feedback, thx a lot!

I think we can solve this still by rendering the MentionSearch inside. Will give it a try right away!

**Comment by nikgraf** [comment]
@filod fixed it by manually implementing this behaviour :bow:

**Comment by filod** [comment]
:+1:
