### ISSUE TITLE
Clicking "Remove" deletes two unicorns

### ISSUE THREAD

**Issue by mxstbr** [nikgraf/draft-js-plugin-editor#7]
Steps to reproduce:

1) Add two (or more) unicorns with no text in between them
2) Click the uppermost "Remove" button

Video: http://cl.ly/3G2c1e2m3C0v

**Comment by mxstbr** [comment]
No idea why this is happening because I don't understand `draft.js` well enough just yet.

**Comment by nikgraf** [comment]
ahhh, good one thx!

**Comment by nikgraf** [comment]
more info: only happens when the first two blocks are stickers
